db/schema.rb

missign mgiration

---

app/models/review.rb
db/migrate/20191118132014_create_reviews.rb
test/models/review_test.rb

create review model

---

app/models/shift.rb
db/migrate/20191118133036_create_shifts.rb
test/models/shift_test.rb

create shift model

---

app/controllers/jobs_controller.rb
test/controllers/jobs_controller_test.rb

Job Controller

---

app/controllers/jobs_controller.rb

Jobs Controller

---

app/controllers/jobs_controller.rb
config/routes.rb

Finished jobs controller_final

Finished Jobs Controller

---

app/controllers/reviews_controller.rb
test/controllers/reviews_controller_test.rb

reviews controller

---

app/controllers/jobs_controller.rb
app/controllers/reviews_controller.rb

Controller Updates

---

app/controllers/jobs_controller.rb

Updated user id

---

app/controllers/jobs_controller.rb
app/controllers/shifts_controller.rb
test/controllers/shifts_controller_test.rb

shifts controller

---

app/controllers/jobs_controller.rb
app/views/jobs/show.html.erb
app/views/shared/_create-shift.html.erb
config/routes.rb

add create shift

---

app/controllers/applications_controller.rb
app/controllers/jobs_controller.rb
app/controllers/reviews_controller.rb
app/models/application.rb
app/views/applications/new.html.erb
config/routes.rb
db/migrate/20191118163917_create_applications.rb
db/schema.rb
test/controllers/applications_controller_test.rb
test/models/application_test.rb

New Application

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Updated sign-in and sign-up

---

app/views/jobs/index.html.erb

search bar without function

---

app/views/applications/new.html.erb
app/views/applications/show.html.erb

just added a request show file

added file

---

app/controllers/application_controller.rb
app/controllers/shifts_controller.rb
app/policies/application_policy.rb
app/policies/shift_policy.rb
app/views/jobs/show.html.erb
app/views/requests/show.html.erb
app/views/shared/_view_requests.html.erb
config/routes.rb

get more details on user application on job. ability to accept a request and add that user to a shift

adding a user to a shift

---

db/migrate/20191119160942_add_completed_to_shifts.rb

added column completed to shifts

---

app/views/pages/dashboard.html.erb
db/schema.rb

Upcoming Jobs

---

app/assets/stylesheets/components/_hidden.scss
app/assets/stylesheets/components/_index.scss
app/controllers/jobs_controller.rb
app/javascript/components/apply.js
app/javascript/packs/application.js
app/policies/shift_policy.rb
app/views/devise/registrations/new.html.erb
app/views/jobs/index.html.erb
app/views/shared/_request.html.erb
app/views/shared/_show-jobs.html.erb
config/application.rb

has js for application and turn show jobs into a modal

Apply flow

---

app/controllers/application_controller.rb
app/controllers/jobs_controller.rb
app/controllers/users_controller.rb
app/views/devise/registrations/new.html.erb
app/views/pages/dashboard_employer.html.erb
app/views/users/edit.html.erb

This basically allows you to sign-up as an employer if you want, if you do it redirects you to the job dashboard and from there you can create new jobs/shifts etc. otherwise you see the job index

Employer-employee

---

app/views/shared/_show-jobs.html.erb

Bug fixed for strftime by adding a lonely operator

---

app/views/jobs/index.html.erb

button to display all job results

return all job results again

---

Gemfile
Gemfile.lock
app/controllers/shifts_controller.rb
app/models/shift.rb
app/views/shared/_create-shift.html.erb
app/views/shared/_each_job_history.html.erb
app/views/shared/_show-jobs.html.erb
app/views/shifts/_edit-shift.html.erb
app/views/shifts/_shift-card-modal.html.erb
app/views/shifts/_shift-card.html.erb
app/views/shifts/show.html.erb
config/initializers/money.rb
db/migrate/20191125105355_add_price_to_shifts.rb
db/migrate/20191125111412_remove_pay_from_shifts.rb
db/schema.rb

Monetise gem added and price has been added to shifts table. Appropriate views also updated to remove pay.

Added price to shifts

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_map.scss
app/views/shifts/_shift-card.html.erb

also corrected formatting on the map pop up

paid icon made

---

app/controllers/requests_controller.rb
app/jobs/close_shifts_job.rb
app/views/jobs/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_listed-jobs.html.erb
app/views/shared/_view_requests.html.erb
app/views/shifts/_shift-card.html.erb
db/migrate/20191129143814_add_completed_to_requests.rb
db/schema.rb

requests have column completed. request auto-removed when shift completed
